"""add deadline date to announcements

Revision ID: 5f4c391df25e
Revises: 3d70b82ff082
Create Date: 2026-08-31 13:52:49.496883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4c391df25e'
down_revision: Union[str, Sequence[str], None] = '3d70b82ff082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('deadline_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'deadline_date')
    # ### end Alembic commands ###
